### ISSUE TITLE
Investigate exceptions in agent logs

### ISSUE THREAD

**Issue by pavolloffay** [hypertrace/javaagent#15]
Debug log shows some exceptions in agent, however agent seems to work fine.

```
OTEL_EXPORTER=jaeger java -Dio.opentelemetry.javaagent.slf4j.simpleLogger.defaultLogLevel=debug  -agentlib:jdwp="transport=dt_socket,server=y,suspend=n,address=5000" -javaagent:${HOME}/projects/hypertrace/opentelemetry-java-agent/javaagent/build/libs/hypertrace-agent-0.0.1-all.jar  -jar target/spring-petclinic-2.3.0.BUILD-SNAPSHOT.jar
```

```bash
java.lang.ClassNotFoundException: io/opentelemetry/javaagent/shaded/io/grpc/override/ContextStorageOverride
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at io.opentelemetry.javaagent.shaded.io.grpc.Context$LazyStorage.createStorage(Context.java:142)
	at io.opentelemetry.javaagent.shaded.io.grpc.Context$LazyStorage.<clinit>(Context.java:131)
	at io.opentelemetry.javaagent.shaded.io.grpc.Context.storage(Context.java:119)
	at io.opentelemetry.javaagent.shaded.io.grpc.Context.current(Context.java:185)
	at io.opentelemetry.javaagent.shaded.io.opentelemetry.trace.TracingContextUtils.getCurrentSpan(TracingContextUtils.java:44)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:255)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	at ch.qos.logback.classic.Logger.log(Logger.java:765)
	at org.apache.commons.logging.LogAdapter$Slf4jLocationAwareLog.info(LogAdapter.java:454)
	at org.springframework.boot.StartupInfoLogger.logStarting(StartupInfoLogger.java:55)
	at org.springframework.boot.SpringApplication.logStartupInfo(SpringApplication.java:637)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.samples.petclinic.PetClinicApplication.main(PetClinicApplication.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)


[opentelemetry.auto.trace 2020-10-10 10:49:58:548 +0200] [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
[opentelemetry.auto.trace 2020-10-10 10:49:58:552 +0200] [main] DEBUG io.grpc.netty.shaded.io.grpc.netty.Utils - Epoll is not available, using Nio.
java.lang.ExceptionInInitializerError
	at io.grpc.netty.shaded.io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at io.grpc.netty.shaded.io.grpc.netty.Utils.isEpollAvailable(Utils.java:220)
	at io.grpc.netty.shaded.io.grpc.netty.Utils.<clinit>(Utils.java:92)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<clinit>(NettyChannelBuilder.java:72)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForTarget(NettyChannelProvider.java:42)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForTarget(NettyChannelProvider.java:23)
	at io.grpc.ManagedChannelBuilder.forTarget(ManagedChannelBuilder.java:76)
	at io.opentelemetry.exporters.jaeger.JaegerGrpcSpanExporter$Builder.build(JaegerGrpcSpanExporter.java:263)
	at io.opentelemetry.javaagent.exporters.jaeger.JaegerExporterFactory.fromConfig(JaegerExporterFactory.java:19)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installExporter(TracerInstaller.java:155)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installExporters(TracerInstaller.java:65)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installAgentTracer(TracerInstaller.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.installAgentTracer(AgentInitializer.java:162)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:64)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.IllegalStateException: Only supported on Linux
	at io.grpc.netty.shaded.io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:180)
	at io.grpc.netty.shaded.io.netty.channel.epoll.Native.<clinit>(Native.java:57)
	... 32 more
[opentelemetry.auto.trace 2020-10-10 10:49:58:565 +0200] [main] DEBUG io.grpc.NameResolverRegistry - Service loader found io.grpc.internal.DnsNameResolverProvider@277bf091
[opentelemetry.auto.trace 2020-10-10 10:49:58:583 +0200] [main] DEBUG io.grpc.netty.shaded.io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 24
[opentelemetry.auto.trace 2020-10-10 10:49:58:597 +0200] [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
[opentelemetry.auto.trace 2020-10-10 10:49:58:597 +0200] [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
[opentelemetry.auto.trace 2020-10-10 10:49:58:605 +0200] [main] DEBUG io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
[opentelemetry.auto.trace 2020-10-10 10:49:58:605 +0200] [main] DEBUG io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
[opentelemetry.auto.trace 2020-10-10 10:49:58:613 +0200] [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
[opentelemetry.auto.trace 2020-10-10 10:49:58:628 +0200] [main] DEBUG io.opencensus.tags.Tags - Couldn't load full implementation for TagsComponent, now trying to load lite implementation.
java.lang.ClassNotFoundException: io.opencensus.impl.tags.TagsComponentImpl
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at io.opencensus.tags.Tags.loadTagsComponent(Tags.java:99)
	at io.opencensus.tags.Tags.<clinit>(Tags.java:35)
	at io.grpc.internal.CensusStatsModule.<init>(CensusStatsModule.java:91)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.getEffectiveInterceptors(AbstractManagedChannelImplBuilder.java:528)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:512)
	at io.opentelemetry.exporters.jaeger.JaegerGrpcSpanExporter$Builder.build(JaegerGrpcSpanExporter.java:263)
	at io.opentelemetry.javaagent.exporters.jaeger.JaegerExporterFactory.fromConfig(JaegerExporterFactory.java:19)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installExporter(TracerInstaller.java:155)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installExporters(TracerInstaller.java:65)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installAgentTracer(TracerInstaller.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.installAgentTracer(AgentInitializer.java:162)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:64)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
[opentelemetry.auto.trace 2020-10-10 10:49:58:629 +0200] [main] DEBUG io.opencensus.tags.Tags - Couldn't load lite implementation for TagsComponent, now using default implementation for TagsComponent.
java.lang.ClassNotFoundException: io.opencensus.impllite.tags.TagsComponentImplLite
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at io.opencensus.tags.Tags.loadTagsComponent(Tags.java:112)
	at io.opencensus.tags.Tags.<clinit>(Tags.java:35)
	at io.grpc.internal.CensusStatsModule.<init>(CensusStatsModule.java:91)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.getEffectiveInterceptors(AbstractManagedChannelImplBuilder.java:528)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:512)
	at io.opentelemetry.exporters.jaeger.JaegerGrpcSpanExporter$Builder.build(JaegerGrpcSpanExporter.java:263)
	at io.opentelemetry.javaagent.exporters.jaeger.JaegerExporterFactory.fromConfig(JaegerExporterFactory.java:19)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installExporter(TracerInstaller.java:155)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installExporters(TracerInstaller.java:65)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installAgentTracer(TracerInstaller.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.installAgentTracer(AgentInitializer.java:162)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:64)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
[opentelemetry.auto.trace 2020-10-10 10:49:58:632 +0200] [main] DEBUG io.opencensus.stats.Stats - Couldn't load full implementation for StatsComponent, now trying to load lite implementation.
java.lang.ClassNotFoundException: io.opencensus.impl.stats.StatsComponentImpl
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at io.opencensus.stats.Stats.loadStatsComponent(Stats.java:97)
	at io.opencensus.stats.Stats.<clinit>(Stats.java:34)
	at io.grpc.internal.CensusStatsModule.<init>(CensusStatsModule.java:93)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.getEffectiveInterceptors(AbstractManagedChannelImplBuilder.java:528)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:512)
	at io.opentelemetry.exporters.jaeger.JaegerGrpcSpanExporter$Builder.build(JaegerGrpcSpanExporter.java:263)
	at io.opentelemetry.javaagent.exporters.jaeger.JaegerExporterFactory.fromConfig(JaegerExporterFactory.java:19)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installExporter(TracerInstaller.java:155)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installExporters(TracerInstaller.java:65)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installAgentTracer(TracerInstaller.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.installAgentTracer(AgentInitializer.java:162)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:64)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
[opentelemetry.auto.trace 2020-10-10 10:49:58:632 +0200] [main] DEBUG io.opencensus.stats.Stats - Couldn't load lite implementation for StatsComponent, now using default implementation for StatsComponent.
java.lang.ClassNotFoundException: io.opencensus.impllite.stats.StatsComponentImplLite
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at io.opencensus.stats.Stats.loadStatsComponent(Stats.java:110)
	at io.opencensus.stats.Stats.<clinit>(Stats.java:34)
	at io.grpc.internal.CensusStatsModule.<init>(CensusStatsModule.java:93)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.getEffectiveInterceptors(AbstractManagedChannelImplBuilder.java:528)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:512)
	at io.opentelemetry.exporters.jaeger.JaegerGrpcSpanExporter$Builder.build(JaegerGrpcSpanExporter.java:263)
	at io.opentelemetry.javaagent.exporters.jaeger.JaegerExporterFactory.fromConfig(JaegerExporterFactory.java:19)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installExporter(TracerInstaller.java:155)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installExporters(TracerInstaller.java:65)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installAgentTracer(TracerInstaller.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.installAgentTracer(AgentInitializer.java:162)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:64)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
[opentelemetry.auto.trace 2020-10-10 10:49:58:642 +0200] [main] DEBUG io.opencensus.trace.Tracing - Couldn't load full implementation for TraceComponent, now trying to load lite implementation.
java.lang.ClassNotFoundException: io.opencensus.impl.trace.TraceComponentImpl
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at io.opencensus.trace.Tracing.loadTraceComponent(Tracing.java:95)
	at io.opencensus.trace.Tracing.<clinit>(Tracing.java:37)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.getEffectiveInterceptors(AbstractManagedChannelImplBuilder.java:539)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:512)
	at io.opentelemetry.exporters.jaeger.JaegerGrpcSpanExporter$Builder.build(JaegerGrpcSpanExporter.java:263)
	at io.opentelemetry.javaagent.exporters.jaeger.JaegerExporterFactory.fromConfig(JaegerExporterFactory.java:19)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installExporter(TracerInstaller.java:155)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installExporters(TracerInstaller.java:65)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installAgentTracer(TracerInstaller.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.installAgentTracer(AgentInitializer.java:162)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:64)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
[opentelemetry.auto.trace 2020-10-10 10:49:58:642 +0200] [main] DEBUG io.opencensus.trace.Tracing - Couldn't load lite implementation for TraceComponent, now using default implementation for TraceComponent.
java.lang.ClassNotFoundException: io.opencensus.impllite.trace.TraceComponentImplLite
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at io.opencensus.trace.Tracing.loadTraceComponent(Tracing.java:108)
	at io.opencensus.trace.Tracing.<clinit>(Tracing.java:37)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.getEffectiveInterceptors(AbstractManagedChannelImplBuilder.java:539)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:512)
	at io.opentelemetry.exporters.jaeger.JaegerGrpcSpanExporter$Builder.build(JaegerGrpcSpanExporter.java:263)
	at io.opentelemetry.javaagent.exporters.jaeger.JaegerExporterFactory.fromConfig(JaegerExporterFactory.java:19)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installExporter(TracerInstaller.java:155)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installExporters(TracerInstaller.java:65)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installAgentTracer(TracerInstaller.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.installAgentTracer(AgentInitializer.java:162)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:64)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
```

**Comment by pavolloffay** [comment]
Done in the upstream
